"""Alembic environment.

Two things this file gets right that a default `alembic init` does not:

1. The database URL comes from application settings, never from alembic.ini,
   so credentials are never in a committed file and local/CI/production all
   use the same resolution path.
2. `compare_type` and `compare_server_default` are on, so autogenerate detects
   column type and default changes instead of silently ignoring them.
3. The CHECK constraints SQLAlchemy generates for our string enums are hidden
   from autogenerate — see `_include_object`.

Migrations are autogenerated and reviewed wherever autogenerate can see the
change. Adding a value to a string enum is the exception: it rewrites a CHECK
constraint, which autogenerate does not detect, so those are written by hand.
A landed migration is never edited either way.
"""

import asyncio
from enum import StrEnum
from logging.config import fileConfig
from typing import Any

from alembic import context
from sqlalchemy import Connection, pool
from sqlalchemy.ext.asyncio import async_engine_from_config
from sqlmodel import SQLModel

# Importing the models package registers every table on SQLModel.metadata.
# Without this import autogenerate produces an empty migration.
import ns.models
import ns.models.enums
from ns.config import get_settings

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

config.set_main_option("sqlalchemy.url", str(get_settings().database_url))

target_metadata = SQLModel.metadata


# The CHECK constraints behind our string enums. SQLAlchemy emits them from
# `Enum(native_enum=False, create_constraint=True)` at DDL time, and names them
# after the enum class, but they are not part of the comparable metadata — so
# autogenerate reflects them from the database, fails to find a counterpart,
# and proposes dropping every one of them.
#
# Applying such a migration would strip the database-level integrity these
# columns exist to have, quietly, in a diff that reads like housekeeping. They
# are excluded here so an autogenerated migration is safe to apply unread.
# Their real changes are hand-written, and any *other* check constraint still
# shows up normally.
_ENUM_CONSTRAINT_NAMES = frozenset(
    name.lower()
    for name, value in vars(ns.models.enums).items()
    if isinstance(value, type) and issubclass(value, StrEnum) and value is not StrEnum
)


def _include_object(
    obj: Any, name: str | None, type_: str, reflected: bool, compare_to: Any
) -> bool:
    """Keep autogenerate focused on changes this project actually manages."""
    if type_ == "table" and name in {"spatial_ref_sys"}:
        return False
    return not (type_ == "check_constraint" and (name or "").lower() in _ENUM_CONSTRAINT_NAMES)


def _configure(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        compare_server_default=True,
        include_object=_include_object,
        render_as_batch=False,  # Postgres supports real ALTER; batch mode is for SQLite
    )


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a live connection (`alembic upgrade --sql`)."""
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def _do_run_migrations(connection: Connection) -> None:
    _configure(connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(_do_run_migrations)

    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
