"""initial schema

Revision ID: f9e80d16951e
Revises:
Create Date: 2026-08-17 22:55:57.499570+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "f9e80d16951e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budget",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_budget_month"), "budget", ["month"], unique=True)
    op.create_table(
        "food",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "canonical_name",
            sqlmodel.sql.sqltypes.AutoString(length=300),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "produce",
                "protein",
                "dairy",
                "grains",
                "packaged",
                "beverages",
                "household",
                "uncategorized",
                name="foodcategory",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("fdc_id", sa.Integer(), nullable=True),
        sa.Column("fdc_data_type", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
        sa.Column("density_g_per_ml", sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column("edible_portion_pct", sa.Numeric(precision=7, scale=3), nullable=False),
        sa.Column("cooked_yield_factor", sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column("usda_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_seed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fdc_id"),
    )
    op.create_index(op.f("ix_food_canonical_name"), "food", ["canonical_name"], unique=False)
    op.create_index(op.f("ix_food_category"), "food", ["category"], unique=False)
    op.create_table(
        "nutrient_reference",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nutrient_code", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
        sa.Column("sex", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
        sa.Column("age_min_years", sa.Integer(), nullable=True),
        sa.Column("age_max_years", sa.Integer(), nullable=True),
        sa.Column("rda_per_day", sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column("upper_limit_per_day", sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_nutrient_reference_nutrient_code"),
        "nutrient_reference",
        ["nutrient_code"],
        unique=False,
    )
    op.create_index(
        "uq_nutrient_reference_scope",
        "nutrient_reference",
        ["nutrient_code", "sex", "age_min_years", "age_max_years"],
        unique=True,
    )
    op.create_table(
        "resolver_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column(
            "prompt_version",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column(
            "normalizer_version",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column("n_examples", sa.Integer(), nullable=False),
        sa.Column("food_accuracy", sa.Float(), nullable=False),
        sa.Column("grams_within_tolerance", sa.Float(), nullable=False),
        sa.Column("precision_at_threshold", sa.Float(), nullable=False),
        sa.Column("confidence_threshold", sa.Float(), nullable=False),
        sa.Column("expected_calibration_error", sa.Float(), nullable=True),
        sa.Column("breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cost_usd_per_receipt", sa.Float(), nullable=True),
        sa.Column("latency_p50_ms", sa.Integer(), nullable=True),
        sa.Column("latency_p95_ms", sa.Integer(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_resolver_run_model_time", "resolver_run", ["model", "run_at"], unique=False)
    op.create_table(
        "store",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
        sa.Column(
            "receipt_format_hints",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_store_name"), "store", ["name"], unique=False)
    op.create_table(
        "correction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "normalized_text",
            sqlmodel.sql.sqltypes.AutoString(length=300),
            nullable=False,
        ),
        sa.Column("store_id", sa.Integer(), nullable=True),
        sa.Column("food_id", sa.Integer(), nullable=True),
        sa.Column("is_nonfood", sa.Boolean(), nullable=False),
        sa.Column(
            "grams_basis",
            sa.Enum(
                "from_receipt",
                "per_package",
                "per_unit_estimate",
                "density",
                "unknown",
                name="gramsbasis",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("grams_value", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("applied_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["food_id"],
            ["food.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["store.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_correction_food_id"), "correction", ["food_id"], unique=False)
    op.create_index(
        op.f("ix_correction_normalized_text"),
        "correction",
        ["normalized_text"],
        unique=False,
    )
    op.create_index(op.f("ix_correction_store_id"), "correction", ["store_id"], unique=False)
    op.create_index(
        "uq_correction_text_store",
        "correction",
        ["normalized_text", "store_id"],
        unique=True,
    )
    # Hand-added: autogenerate cannot infer this. Postgres treats NULLs as
    # distinct in a unique index, so the index above does NOT prevent two
    # global corrections (store_id IS NULL) for the same text, and tier-1b
    # resolution could then match either of two conflicting rows.
    # See DECISIONS.md D2.
    op.create_index(
        "uq_correction_text_global",
        "correction",
        ["normalized_text"],
        unique=True,
        postgresql_where=sa.text("store_id IS NULL"),
    )
    op.create_table(
        "food_nutrient",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("food_id", sa.Integer(), nullable=False),
        sa.Column("nutrient_code", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
        sa.Column("amount_per_100g", sa.Numeric(precision=7, scale=3), nullable=False),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
        sa.ForeignKeyConstraint(["food_id"], ["food.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_food_nutrient_food_id"), "food_nutrient", ["food_id"], unique=False)
    op.create_index(
        op.f("ix_food_nutrient_nutrient_code"),
        "food_nutrient",
        ["nutrient_code"],
        unique=False,
    )
    op.create_index(
        "uq_food_nutrient_food_code",
        "food_nutrient",
        ["food_id", "nutrient_code"],
        unique=True,
    )
    op.create_table(
        "receipt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image_sha256", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("image_path", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("image_bytes", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=True),
        sa.Column("purchased_at", sa.Date(), nullable=True),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
        sa.Column("subtotal_cents", sa.Integer(), nullable=True),
        sa.Column("tax_cents", sa.Integer(), nullable=True),
        sa.Column("total_cents", sa.Integer(), nullable=True),
        sa.Column("raw_extraction", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "extraction_model",
            sqlmodel.sql.sqltypes.AutoString(length=80),
            nullable=True,
        ),
        sa.Column(
            "extraction_prompt_version",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=True,
        ),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "extracting",
                "extract_failed",
                "normalized",
                "reconciled",
                "resolving",
                "needs_review",
                "complete",
                name="pipelinestatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "reconciliation_status",
            sa.Enum(
                "not_attempted",
                "balanced",
                "suspect",
                "unreconcilable",
                name="reconciliationstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reconciliation_delta_cents", sa.Integer(), nullable=True),
        sa.Column(
            "reconciliation_report",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("duplicate_of_receipt_id", sa.Integer(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["duplicate_of_receipt_id"],
            ["receipt.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["store.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_receipt_duplicate_of_receipt_id"),
        "receipt",
        ["duplicate_of_receipt_id"],
        unique=False,
    )
    op.create_index(op.f("ix_receipt_image_sha256"), "receipt", ["image_sha256"], unique=True)
    op.create_index(op.f("ix_receipt_purchased_at"), "receipt", ["purchased_at"], unique=False)
    op.create_index(
        op.f("ix_receipt_reconciliation_status"),
        "receipt",
        ["reconciliation_status"],
        unique=False,
    )
    op.create_index(op.f("ix_receipt_status"), "receipt", ["status"], unique=False)
    op.create_index(
        "ix_receipt_store_date_total",
        "receipt",
        ["store_id", "purchased_at", "total_cents"],
        unique=False,
    )
    op.create_index(op.f("ix_receipt_store_id"), "receipt", ["store_id"], unique=False)
    op.create_table(
        "store_alias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("alias_text", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["store_id"], ["store.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_store_alias_alias_text"), "store_alias", ["alias_text"], unique=True)
    op.create_index(op.f("ix_store_alias_store_id"), "store_alias", ["store_id"], unique=False)
    op.create_table(
        "line_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("receipt_id", sa.Integer(), nullable=False),
        sa.Column("line_index", sa.Integer(), nullable=False),
        sa.Column("raw_text", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column(
            "normalized_text",
            sqlmodel.sql.sqltypes.AutoString(length=300),
            nullable=False,
        ),
        sa.Column(
            "normalizer_version",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "product",
                "discount",
                "fee",
                "tax",
                "subtotal",
                "total",
                "unknown",
                name="lineitemkind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("grams_as_purchased", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("grams_edible", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column(
            "grams_basis",
            sa.Enum(
                "from_receipt",
                "per_package",
                "per_unit_estimate",
                "density",
                "unknown",
                name="gramsbasis",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "edible_portion_pct_applied",
            sa.Numeric(precision=7, scale=3),
            nullable=True,
        ),
        sa.Column("food_id", sa.Integer(), nullable=True),
        sa.Column(
            "resolution_source",
            sa.Enum(
                "correction_store",
                "correction_global",
                "llm",
                "unresolved",
                "nonfood",
                name="resolutionsource",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("discount_cents", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["food_id"],
            ["food.id"],
        ),
        sa.ForeignKeyConstraint(["receipt_id"], ["receipt.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_line_item_food_id"), "line_item", ["food_id"], unique=False)
    op.create_index(op.f("ix_line_item_kind"), "line_item", ["kind"], unique=False)
    op.create_index(
        op.f("ix_line_item_normalized_text"),
        "line_item",
        ["normalized_text"],
        unique=False,
    )
    op.create_index(op.f("ix_line_item_receipt_id"), "line_item", ["receipt_id"], unique=False)
    op.create_index(
        op.f("ix_line_item_resolution_source"),
        "line_item",
        ["resolution_source"],
        unique=False,
    )
    op.create_index(
        "ix_line_item_unresolved",
        "line_item",
        ["normalized_text"],
        unique=False,
        postgresql_where="food_id IS NULL",
    )
    op.create_index(
        "uq_line_item_receipt_index",
        "line_item",
        ["receipt_id", "line_index"],
        unique=True,
    )
    op.create_table(
        "llm_call",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("receipt_id", sa.Integer(), nullable=True),
        sa.Column("resolver_run_id", sa.Integer(), nullable=True),
        sa.Column(
            "stage",
            sa.Enum(
                "extract",
                "resolve",
                "eval",
                name="llmstage",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column("prompt_version", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("called_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_write_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("error_type", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("stop_reason", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
        sa.ForeignKeyConstraint(["receipt_id"], ["receipt.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["resolver_run_id"], ["resolver_run.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_call_receipt_id"), "llm_call", ["receipt_id"], unique=False)
    op.create_index(
        op.f("ix_llm_call_resolver_run_id"),
        "llm_call",
        ["resolver_run_id"],
        unique=False,
    )
    op.create_index(op.f("ix_llm_call_stage"), "llm_call", ["stage"], unique=False)
    op.create_index("ix_llm_call_stage_time", "llm_call", ["stage", "called_at"], unique=False)
    op.create_table(
        "eval_example",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raw_text", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column(
            "normalized_text",
            sqlmodel.sql.sqltypes.AutoString(length=300),
            nullable=False,
        ),
        sa.Column(
            "normalizer_version",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column("store_id", sa.Integer(), nullable=True),
        sa.Column("expected_food_id", sa.Integer(), nullable=True),
        sa.Column("expected_is_nonfood", sa.Boolean(), nullable=False),
        sa.Column("expected_grams", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column(
            "expected_grams_basis",
            sa.Enum(
                "from_receipt",
                "per_package",
                "per_unit_estimate",
                "density",
                "unknown",
                name="gramsbasis",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "label_source",
            sa.Enum(
                "corrected",
                "confirmed",
                name="labelsource",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "split",
            sa.Enum(
                "train",
                "holdout",
                name="evalsplit",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_line_item_id", sa.Integer(), nullable=True),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["expected_food_id"],
            ["food.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_line_item_id"],
            ["line_item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["store.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_eval_example_expected_food_id"),
        "eval_example",
        ["expected_food_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_eval_example_label_source"),
        "eval_example",
        ["label_source"],
        unique=False,
    )
    op.create_index(
        op.f("ix_eval_example_normalized_text"),
        "eval_example",
        ["normalized_text"],
        unique=False,
    )
    op.create_index(
        op.f("ix_eval_example_source_line_item_id"),
        "eval_example",
        ["source_line_item_id"],
        unique=False,
    )
    op.create_index(op.f("ix_eval_example_split"), "eval_example", ["split"], unique=False)
    op.create_index(op.f("ix_eval_example_store_id"), "eval_example", ["store_id"], unique=False)
    op.create_table(
        "price_observation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("line_item_id", sa.Integer(), nullable=False),
        sa.Column("food_id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=True),
        sa.Column("observed_at", sa.Date(), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column("grams", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("price_cents_per_100g", sa.Numeric(precision=7, scale=3), nullable=False),
        sa.Column(
            "grams_basis",
            sa.Enum(
                "from_receipt",
                "per_package",
                "per_unit_estimate",
                "density",
                "unknown",
                name="gramsbasis",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("was_discounted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["food_id"],
            ["food.id"],
        ),
        sa.ForeignKeyConstraint(["line_item_id"], ["line_item.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["store.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_price_obs_food_store_date",
        "price_observation",
        ["food_id", "store_id", "observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_observation_food_id"),
        "price_observation",
        ["food_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_observation_line_item_id"),
        "price_observation",
        ["line_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_observation_observed_at"),
        "price_observation",
        ["observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_observation_store_id"),
        "price_observation",
        ["store_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_observation_was_discounted"),
        "price_observation",
        ["was_discounted"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_price_observation_was_discounted"), table_name="price_observation")
    op.drop_index(op.f("ix_price_observation_store_id"), table_name="price_observation")
    op.drop_index(op.f("ix_price_observation_observed_at"), table_name="price_observation")
    op.drop_index(op.f("ix_price_observation_line_item_id"), table_name="price_observation")
    op.drop_index(op.f("ix_price_observation_food_id"), table_name="price_observation")
    op.drop_index("ix_price_obs_food_store_date", table_name="price_observation")
    op.drop_table("price_observation")
    op.drop_index(op.f("ix_eval_example_store_id"), table_name="eval_example")
    op.drop_index(op.f("ix_eval_example_split"), table_name="eval_example")
    op.drop_index(op.f("ix_eval_example_source_line_item_id"), table_name="eval_example")
    op.drop_index(op.f("ix_eval_example_normalized_text"), table_name="eval_example")
    op.drop_index(op.f("ix_eval_example_label_source"), table_name="eval_example")
    op.drop_index(op.f("ix_eval_example_expected_food_id"), table_name="eval_example")
    op.drop_table("eval_example")
    op.drop_index("ix_llm_call_stage_time", table_name="llm_call")
    op.drop_index(op.f("ix_llm_call_stage"), table_name="llm_call")
    op.drop_index(op.f("ix_llm_call_resolver_run_id"), table_name="llm_call")
    op.drop_index(op.f("ix_llm_call_receipt_id"), table_name="llm_call")
    op.drop_table("llm_call")
    op.drop_index("uq_line_item_receipt_index", table_name="line_item")
    op.drop_index(
        "ix_line_item_unresolved",
        table_name="line_item",
        postgresql_where="food_id IS NULL",
    )
    op.drop_index(op.f("ix_line_item_resolution_source"), table_name="line_item")
    op.drop_index(op.f("ix_line_item_receipt_id"), table_name="line_item")
    op.drop_index(op.f("ix_line_item_normalized_text"), table_name="line_item")
    op.drop_index(op.f("ix_line_item_kind"), table_name="line_item")
    op.drop_index(op.f("ix_line_item_food_id"), table_name="line_item")
    op.drop_table("line_item")
    op.drop_index(op.f("ix_store_alias_store_id"), table_name="store_alias")
    op.drop_index(op.f("ix_store_alias_alias_text"), table_name="store_alias")
    op.drop_table("store_alias")
    op.drop_index(op.f("ix_receipt_store_id"), table_name="receipt")
    op.drop_index("ix_receipt_store_date_total", table_name="receipt")
    op.drop_index(op.f("ix_receipt_status"), table_name="receipt")
    op.drop_index(op.f("ix_receipt_reconciliation_status"), table_name="receipt")
    op.drop_index(op.f("ix_receipt_purchased_at"), table_name="receipt")
    op.drop_index(op.f("ix_receipt_image_sha256"), table_name="receipt")
    op.drop_index(op.f("ix_receipt_duplicate_of_receipt_id"), table_name="receipt")
    op.drop_table("receipt")
    op.drop_index("uq_food_nutrient_food_code", table_name="food_nutrient")
    op.drop_index(op.f("ix_food_nutrient_nutrient_code"), table_name="food_nutrient")
    op.drop_index(op.f("ix_food_nutrient_food_id"), table_name="food_nutrient")
    op.drop_table("food_nutrient")
    op.drop_index("uq_correction_text_global", table_name="correction")
    op.drop_index("uq_correction_text_store", table_name="correction")
    op.drop_index(op.f("ix_correction_store_id"), table_name="correction")
    op.drop_index(op.f("ix_correction_normalized_text"), table_name="correction")
    op.drop_index(op.f("ix_correction_food_id"), table_name="correction")
    op.drop_table("correction")
    op.drop_index(op.f("ix_store_name"), table_name="store")
    op.drop_table("store")
    op.drop_index("ix_resolver_run_model_time", table_name="resolver_run")
    op.drop_table("resolver_run")
    op.drop_index("uq_nutrient_reference_scope", table_name="nutrient_reference")
    op.drop_index(op.f("ix_nutrient_reference_nutrient_code"), table_name="nutrient_reference")
    op.drop_table("nutrient_reference")
    op.drop_index(op.f("ix_food_category"), table_name="food")
    op.drop_index(op.f("ix_food_canonical_name"), table_name="food")
    op.drop_table("food")
    op.drop_index(op.f("ix_budget_month"), table_name="budget")
    op.drop_table("budget")
    # ### end Alembic commands ###
