"""unique canonical food name

Resolution keys foods on `canonical_name`, so two rows sharing one would split
that food's price history in half and make cost per gram of protein quietly
wrong for both. Uniqueness is what makes "use the same name for the same food"
an enforced fact rather than a request in a prompt.


Revision ID: cf1e70385be7
Revises: 97b431249887
Create Date: 2026-08-18 20:08:23.742202+00:00

"""

from collections.abc import Sequence

from alembic import op

revision: str = "cf1e70385be7"
down_revision: str | None = "97b431249887"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_food_canonical_name"), table_name="food")
    op.create_index(
        op.f("ix_food_canonical_name"), "food", ["canonical_name"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_food_canonical_name"), table_name="food")
    op.create_index(
        op.f("ix_food_canonical_name"), "food", ["canonical_name"], unique=False
    )
    # ### end Alembic commands ###
