"""store display name

`store.name` is normalised for matching — lowercased, punctuation collapsed,
corporate suffixes dropped — which makes it a key rather than a label.
Rendering it to a person produced "applies only at costco wholesale", and the
printed casing had already been discarded and could not be recovered.

Nullable, with no backfill in SQL: a store identified before this migration
falls back to the normalised name, and fills its display name in the next time
a receipt from that store is normalised. Healing in code rather than here
means the value comes from a real printed header instead of a guess made by
re-casing the key.


Revision ID: e2a71b6c52ab
Revises: 8afa44d6e774
Create Date: 2026-08-20 20:07:14.449991+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "e2a71b6c52ab"
down_revision: str | None = "8afa44d6e774"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "store",
        sa.Column(
            "display_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("store", "display_name")
    # ### end Alembic commands ###
